Feature/boilerplate generation
ONSdigital/dp-cantabular-dimension-api pull request #1
Opened 2022-01-10 09:10 UTC by ChrysmOre

# What
Inital boilerplate generation and refactor

# How
Check changes make sense

# Who 
Anyone

2022-01-11 13:59 UTC, redhug1 commented on .gitignore
> +*.iws
Add CR

2022-01-11 13:59 UTC, redhug1 commented on Makefile
> +	go test -cover -coverpkg=github.com/ONSdigital/dp-cantabular-dimension-api/... -component
Add CR

2022-01-11 14:00 UTC, redhug1 commented on ci/audit.yml
> +  path: dp-cantabular-dimension-api/ci/scripts/audit.sh
Add CR

2022-01-11 14:00 UTC, redhug1 commented on ci/lint.yml
> +  path: dp-cantabular-dimension-api/ci/scripts/lint.sh
Add CR

2022-01-11 14:00 UTC, redhug1 commented on ci/scripts/audit.sh
> +popd
Add CR

2022-01-11 14:00 UTC, redhug1 commented on ci/scripts/lint.sh
> +popd
Add CR

2022-01-11 14:00 UTC, redhug1 commented on dp-cantabular-dimension-api.nomad
> +}
Add CR

2022-01-11 14:00 UTC, redhug1 commented on features/helloworld.feature
> +    Then I should receive a hello-world response
Add CR

2022-01-11 14:01 UTC, redhug1 commented on swagger.yaml
> +        example: "2019-09-22T11:48:51.0000001Z"
Add CR

2022-01-11 14:01 UTC, redhug1 commented on Dockerfile.local
> +WORKDIR /dp-cantabular-dimension-api
Add CR

2022-01-11 14:02 UTC, redhug1 requested changes
Looks fine, apart from the usual github request for additional CR's at end of file ...

2022-01-11 14:27 UTC, ChrysmOre commented on .gitignore
> +*.iws
All these files come out of code generation without CRs.. amazing

2022-01-11 15:35 UTC, redhug1 approved these changes, later dismissed

2022-01-12 16:08 UTC, DavidSubiros approved these changes
LGTM and CI stuff has been fixed

2022-01-12 16:11 UTC, merged