Release/1.0.0
ONSdigital/dp-cantabular-dimension-api pull request #4
Opened 2022-02-24 14:40 UTC by ChrysmOre

### What

Initial release for service, include first endpoint GET /area-types

### How to review

Check nothing glaringly obvious is wrong

### Who can review

Anyone

2022-03-02 10:35 UTC, franmoore05 approved these changes, later dismissed
LGTM

2022-03-02 12:06 UTC, PauloPortugal requested changes
Please review the `CANTABULAR_API_EXT_URL` environment variable as I believe this is not correct.

2022-03-02 12:06 UTC, PauloPortugal commented on config/config.go
> +	CantabularExtURL             string        `envconfig:"CANTABULAR_EXT_API_URL"`
```suggestion
	CantabularExtURL             string        `envconfig:"CANTABULAR_API_EXT_URL"`
```

2022-03-24 16:22 UTC, PauloPortugal submitted a review, later dismissed

2022-03-28 14:50 UTC, PauloPortugal approved these changes

2022-03-28 15:03 UTC, merged